(* This is just for an overview and not to be used by parser generators, as I desipse them *)

(* TOKENS AND HELPERS *)

helper_digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
helper_alph = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" 
                  | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A"
                  | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" 
                  | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z";


val_int = helper_digit, { helper_digit } ;
val_float = { helper_digit }, ".",  helper_digit, { helper_digit } ;
val_string = '"', { ? any character without unescaped '"' ? },  '"' ;
val_char = "'",   [ "\\" ], ? any character ?,  "'" ;
kw = "return" | "u8" | "u32" | "f32" | "bool" | "mut" | "true" | "false" | "if" | "else" ;
type_kw = "u8" | "u32" | "f32" | "bool" ;
identifier = ( helper_alph|"_" , {helper_alph|helper_digit|"_"} ) - kw;


(* START *)
file = { func_def };

func_def = [typeexpr], identifier, "(", (")" | [param_deftuple]), stmt;

typeexpr = "[", expr, "]", typeexpr 
         | "*", typeexpr
         | "&", typeexpr
         | type_kw
         | identifier;

param_deftuple = { param_singledef, "," }, param_singledef, ")";

param_singledef = typeexpr, identifier;

stmt                = "{", stmt_execblock
                    | "if", (stmt_if | stmt_if_else)
                    | "return", stmt_return

                    (* the complex cases: *)
                    | "mut", stmt_assign,
                    | expr,
                    | stmt_assign;

                    

stmt_execblock      = { stmt }, "}";
stmt_if             = expr, stmt;
stmt_if_else        = expr, stmt, "else", stmt;
stmt_return         = [ expr ];
stmt_assign         = typeexpr, identifier, "=", expr
                    | identifier, "=", expr;


param_calltuple  = "(", { expr, "," }, expr,  ")";

expr            = "(", expr_parens
                | op_unary, expr_op_unary
                | identifier | val_int | val_float | val_string | val_char | "true" | "false"
                | expr, "[", ("]" | expr_indexing)
                | expr, "(", (")" | expr_funccall)
                | op_binary, expr_op_binary;

expr_parens     = expr, ")";
expr_indexing   = expr, "]";
expr_op_binary  = expr;
expr_op_unary   = expr;
expr_funccall   = { expr, "," }, expr, ")";