const Parser = @import("../Parser.zig");
const Lexer = @import("../Lexer.zig");
const ParseTree = @import("../ParseTree.zig");
const FixedStack = @import("../ds/fixedstack.zig").FixedStack;
const NodeId = ParseTree.NodeId;
const eval = @import("eval.zig");

pub const pre = blk: {
    var t: [256]?*const fn (parser: *Parser) anyerror!NodeId = @splat(null);
    t[@intFromEnum(Lexer.Token.Kind.@"pct_(")] = &eval.paren;
    t[@intFromEnum(Lexer.Token.Kind.@"pct_[")] = &eval.bracket;
    t[@intFromEnum(Lexer.Token.Kind.kw_typeof)] = &eval.typeof;
    t[@intFromEnum(Lexer.Token.Kind.kw_sizeof)] = &eval.sizeof;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_-")] = &eval.neg_num;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_!")] = &eval.neg_logic;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_++")] = &eval.inc_prefix;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_--")] = &eval.dec_prefix;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_..=")] = &eval.gen_upperbound_incl;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_..<")] = &eval.gen_upperbound_excl;
    t[@intFromEnum(Lexer.Token.Kind.kw_self)] = &eval.identifier_self;
    t[@intFromEnum(Lexer.Token.Kind.kw_init)] = &eval.identifier_init;
    t[@intFromEnum(Lexer.Token.Kind.kw_main)] = &eval.identifier_main;
    t[@intFromEnum(Lexer.Token.Kind.kw_true)] = &eval.true_;
    t[@intFromEnum(Lexer.Token.Kind.kw_false)] = &eval.false_;
    t[@intFromEnum(Lexer.Token.Kind.kw_do)] = &eval.do;
    t[@intFromEnum(Lexer.Token.Kind.kw_deinit)] = &eval.deinit;
    t[@intFromEnum(Lexer.Token.Kind.kw_defer)] = &eval.defer_;
    t[@intFromEnum(Lexer.Token.Kind.kw_cont)] = &eval.cont;
    t[@intFromEnum(Lexer.Token.Kind.kw_brk)] = &eval.brk;
    t[@intFromEnum(Lexer.Token.Kind.kw_ret)] = &eval.ret;
    t[@intFromEnum(Lexer.Token.Kind.kw_if)] = &eval.if_;
    t[@intFromEnum(Lexer.Token.Kind.kw_while)] = &eval.while_;
    t[@intFromEnum(Lexer.Token.Kind.kw_for)] = &eval.for_;
    t[@intFromEnum(Lexer.Token.Kind.kw_loop)] = &eval.loop;
    t[@intFromEnum(Lexer.Token.Kind.kw_match)] = &eval.match;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_&")] = &eval.type_ptr;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_*")] = &eval.type_ptrmut;
    t[@intFromEnum(Lexer.Token.Kind.kw_u8)] = &eval.type_u8;
    t[@intFromEnum(Lexer.Token.Kind.kw_u16)] = &eval.type_u16;
    t[@intFromEnum(Lexer.Token.Kind.kw_u32)] = &eval.type_u32;
    t[@intFromEnum(Lexer.Token.Kind.kw_u64)] = &eval.type_u64;
    t[@intFromEnum(Lexer.Token.Kind.kw_i8)] = &eval.type_i8;
    t[@intFromEnum(Lexer.Token.Kind.kw_i16)] = &eval.type_i16;
    t[@intFromEnum(Lexer.Token.Kind.kw_i32)] = &eval.type_i32;
    t[@intFromEnum(Lexer.Token.Kind.kw_i64)] = &eval.type_i64;
    t[@intFromEnum(Lexer.Token.Kind.kw_f16)] = &eval.type_f16;
    t[@intFromEnum(Lexer.Token.Kind.kw_f32)] = &eval.type_f32;
    t[@intFromEnum(Lexer.Token.Kind.kw_f64)] = &eval.type_f64;
    t[@intFromEnum(Lexer.Token.Kind.kw_bool)] = &eval.type_bool;
    t[@intFromEnum(Lexer.Token.Kind.kw_type)] = &eval.type_type;
    t[@intFromEnum(Lexer.Token.Kind.kw_trait)] = &eval.type_trait;
    t[@intFromEnum(Lexer.Token.Kind.kw_variant)] = &eval.type_variant;
    t[@intFromEnum(Lexer.Token.Kind.kw_inlfun)] = &eval.type_inlfun;
    t[@intFromEnum(Lexer.Token.Kind.kw_fun)] = &eval.type_fun;
    t[@intFromEnum(Lexer.Token.Kind.kw_stcfun)] = &eval.type_stcfun;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_*(")] = &eval.type_;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_**(")] = &eval.type_;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_+(")] = &eval.variant;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_++(")] = &eval.variant;
    t[@intFromEnum(Lexer.Token.Kind.kw_implof)] = &eval.trait;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_!{")] = &eval.trait;
    t[@intFromEnum(Lexer.Token.Kind.identifier)] = &eval.identifier;
    t[@intFromEnum(Lexer.Token.Kind.val_string)] = &eval.string;
    t[@intFromEnum(Lexer.Token.Kind.val_int)] = &eval.int;
    t[@intFromEnum(Lexer.Token.Kind.val_float)] = &eval.float;
    t[@intFromEnum(Lexer.Token.Kind.val_char)] = &eval.char;
    break :blk t;
};

pub const post = blk: {
    var t: [256]?*const fn (parser: *Parser, lhs: u32) anyerror!u32 = @splat(null);
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_||")] = &eval.unify_variants;
    t[@intFromEnum(Lexer.Token.Kind.@"pct_(")] = &eval.fun_call;
    t[@intFromEnum(Lexer.Token.Kind.@"pct_[")] = &eval.array_index;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_.")] = &eval.member;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_.*")] = &eval.dereference;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_.&")] = &eval.address_of;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_++")] = &eval.inc_postfix;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_--")] = &eval.dec_postfix;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_..")] = &eval.gen_lowerbound;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_..=")] = &eval.gen_incl;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_..<")] = &eval.gen_excl;
    t[@intFromEnum(Lexer.Token.Kind.kw_oftype)] = &eval.oftype;
    t[@intFromEnum(Lexer.Token.Kind.kw_as)] = &eval.as;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_<-")] = &eval.labelarrow;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_?<-")] = &eval.optarrow;
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_??")] = &eval.selftag_unwrap;
    t[@intFromEnum(Lexer.Token.Kind.kw_defer)] = &eval.inlined_defer_deinit;
    t[@intFromEnum(Lexer.Token.Kind.kw_with)] = &eval.with;
    break :blk t;
};

pub const binary_compute = blk: {
    var t: [256]?struct {
        f: *const fn (parser: *Parser, lhs: NodeId) anyerror!NodeId,
        prec: u8,
    } = @splat(null);

    t[@intFromEnum(Lexer.Token.Kind.kw_or)] = .{ .f = &eval.templ_binary(.binary_logic_or, 1), .prec = 1 };
    t[@intFromEnum(Lexer.Token.Kind.kw_xor)] = .{ .f = &eval.templ_binary(.binary_logic_xor, 2), .prec = 2 };
    t[@intFromEnum(Lexer.Token.Kind.kw_and)] = .{ .f = &eval.templ_binary(.binary_logic_and, 3), .prec = 3 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_|")] = .{ .f = &eval.templ_binary(.binary_num_or, 4), .prec = 4 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_^")] = .{ .f = &eval.templ_binary(.binary_num_xor, 5), .prec = 5 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_&")] = .{ .f = &eval.templ_binary(.binary_num_and, 6), .prec = 6 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_==")] = .{ .f = &eval.templ_binary(.binary_eq, 7), .prec = 7 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_!=")] = .{ .f = &eval.templ_binary(.binary_neq, 7), .prec = 7 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_<")] = .{ .f = &eval.templ_binary(.binary_less, 8), .prec = 8 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_>")] = .{ .f = &eval.templ_binary(.binary_greater, 8), .prec = 8 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_<=")] = .{ .f = &eval.templ_binary(.binary_less_eq, 8), .prec = 8 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_>=")] = .{ .f = &eval.templ_binary(.binary_greater_eq, 8), .prec = 8 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_<<")] = .{ .f = &eval.templ_binary(.binary_shift_left, 9), .prec = 9 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_>>")] = .{ .f = &eval.templ_binary(.binary_shift_right, 9), .prec = 9 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_+")] = .{ .f = &eval.templ_binary(.binary_add, 10), .prec = 10 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_-")] = .{ .f = &eval.templ_binary(.binary_sub, 10), .prec = 10 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_*")] = .{ .f = &eval.templ_binary(.binary_mul, 11), .prec = 11 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_/")] = .{ .f = &eval.templ_binary(.binary_div, 11), .prec = 11 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_%")] = .{ .f = &eval.templ_binary(.binary_mod, 11), .prec = 11 };
    t[@intFromEnum(Lexer.Token.Kind.@"xpct_**")] = .{ .f = &eval.templ_binary(.binary_pow, 12), .prec = 12 };

    break :blk t;
};
