
#tool for generating standard.h from standard.mon

print("*** starting generatestandard.py ***")

f = open("standard.mon", "r")
stdf = open("../src/standard.h", "w")
stdf.write("#ifndef STANDARD_H\n#define STANDARD_H\n\n")
stdf.write("//generated by generatestandard.py\n\n")
stdf.write("const char standardlibtext[] =\n")

for i in f.readlines():
    if i != "\n":
        print(i[:-1])
        stdf.write("    \"" + i[:-1] + "\\n\"\n")

stdf.write(";\n\n#endif")

f.close()
stdf.close()

print("copying into ../standard.h done...")