name: ci 
You can change the name to your liking.

on:
  push:
    branches:
      - master 
At some point, GitHub renamed master to main. If your default branch is named master, you can safely remove main, vice versa.

      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
This is the place to install further MkDocs plugins or Markdown exte
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
